### ISSUE TITLE
PWD crashed?

### ISSUE THREAD

**Issue by rcjsuen** [play-with-docker/play-with-docker#167]
Today I accessed PWD on my iPhone and edited and built a small Docker image to test something. When I returned home to use PWD on my browser, I noticed that the website wasn't responding. I decided to open up Safari on my iPhone and my session promptly died and I was greeted with this log file on my phone.

```
PANIC: runtime error: invalid memory address or nil pointer dereference
goroutine 1606547 [running]:
github.com/urfave/negroni.(*Recovery).ServeHTTP.func1(0x7f7f432fff60, 0xc4fe380df0, 0xc420147f50)
	/go/src/github.com/urfave/negroni/recovery.go:41 +0x13a
panic(0xa24fc0, 0xdfc1f0)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/play-with-docker/play-with-docker/pwd/types.(*Session).Lock(0x0)
	/go/src/github.com/play-with-docker/play-with-docker/pwd/types/session.go:28 +0x22
github.com/play-with-docker/play-with-docker/pwd.(*pwd).prepareSession(0xc42019fe40, 0x0, 0x0, 0x0)
	/go/src/github.com/play-with-docker/play-with-docker/pwd/session.go:290 +0x58
github.com/play-with-docker/play-with-docker/pwd.(*pwd).SessionGet(0xc42019fe40, 0xc421d62787, 0x24, 0x0)
	/go/src/github.com/play-with-docker/play-with-docker/pwd/session.go:189 +0xc7
github.com/play-with-docker/play-with-docker/handlers.Home(0x7f7f432fff60, 0xc4fe380df0, 0xc45790d900)
	/go/src/github.com/play-with-docker/play-with-docker/handlers/home.go:13 +0x8f
net/http.HandlerFunc.ServeHTTP(0xb04fd0, 0x7f7f432fff60, 0xc4fe380df0, 0xc45790d900)
	/usr/local/go/src/net/http/server.go:1942 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc42048a910, 0x7f7f432fff60, 0xc4fe380df0, 0xc45790d900)
	/go/src/github.com/gorilla/mux/mux.go:114 +0x10c
github.com/urfave/negroni.Wrap.func1(0x7f7f432fff60, 0xc4fe380df0, 0xc44d98ee00, 0xc476973260)
	/go/src/github.com/urfave/negroni/negroni.go:46 +0x4d
github.com/urfave/negroni.HandlerFunc.ServeHTTP(0xc4201c5c00, 0x7f7f432fff60, 0xc4fe380df0, 0xc44d98ee00, 0xc476973260)
	/go/src/github.com/urfave/negroni/negroni.go:29 +0x4e
github.com/urfave/negroni.middleware.ServeHTTP(0xdc7060, 0xc4201c5c00, 0xc4201c5c80, 0x7f7f432fff60, 0xc4fe380df0, 0xc44d98ee00)
	/go/src/github.com/urfave/negroni/negroni.go:38 +0xb4
github.com/urfave/negroni.(middleware).ServeHTTP-fm(0x7f7f432fff60, 0xc4fe380df0, 0xc44d98ee00)
	/go/src/github.com/urfave/negroni/negroni.go:38 +0x60
github.com/urfave/negroni.(*Static).ServeHTTP(0xc4201cc540, 0x7f7f432fff60, 0xc4fe380df0, 0xc44d98ee00, 0xc476973240)
	/go/src/github.com/urfave/negroni/static.go:53 +0x71c
github.com/urfave/negroni.middleware.ServeHTTP(0xdc4ee0, 0xc4201cc540, 0xc4201c5c60, 0x7f7f432fff60, 0xc4fe380df0, 0xc44d98ee00)
	/go/src/github.com/urfave/negroni/negroni.go:38 +0xb4
github.com/urfave/negroni.(middleware).ServeHTTP-fm(0x7f7f432fff60, 0xc4fe380df0, 0xc44d98ee00)
	/go/src/github.com/urfave/negroni/negroni.go:38 +0x60
github.com/urfave/negroni.(*Logger).ServeHTTP(0xc420147f80, 0x7f7f432fff60, 0xc4fe380df0, 0xc44d98ee00, 0xc476973220)
	/go/src/github.com/urfave/negroni/logger.go:65 +0x89
github.com/urfave/negroni.middleware.ServeHTTP(0xdc4e20, 0xc420147f80, 0xc4201c5c40, 0x7f7f432fff60, 0xc4fe380df0, 0xc44d98ee00)
	/go/src/github.com/urfave/negroni/negroni.go:38 +0xb4
github.com/urfave/negroni.(middleware).ServeHTTP-fm(0x7f7f432fff60, 0xc4fe380df0, 0xc44d98ee00)
	/go/src/github.com/urfave/negroni/negroni.go:38 +0x60
github.com/urfave/negroni.(*Recovery).ServeHTTP(0xc420147f50, 0x7f7f432fff60, 0xc4fe380df0, 0xc44d98ee00, 0xc476973200)
	/go/src/github.com/urfave/negroni/recovery.go:64 +0x82
github.com/urfave/negroni.middleware.ServeHTTP(0xdc4ea0, 0xc420147f50, 0xc4201c5c20, 0x7f7f432fff60, 0xc4fe380df0, 0xc44d98ee00)
	/go/src/github.com/urfave/negroni/negroni.go:38 +0xb4
github.com/urfave/negroni.(*Negroni).ServeHTTP(0xc4201cc5a0, 0xdcc0a0, 0xc421d38620, 0xc44d98ee00)
	/go/src/github.com/urfave/negroni/negroni.go:86 +0x10d
net/http.serverHandler.ServeHTTP(0xc42009d550, 0xdcc0a0, 0xc421d38620, 0xc44d98ee00)
	/usr/local/go/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc44805f0e0, 0xdccb60, 0xc420866fc0)
	/usr/local/go/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2668 +0x2ce
```

**Comment by lucj** [comment]
I cannot access PWD neither.

**Comment by marcosnils** [comment]
It's up now. Sorry for the inconveniences!.

**Comment by lucj** [comment]
Thanks @marcosnils
