### ISSUE TITLE
How to Upload Play with Docker environment on AWS?

### ISSUE THREAD

**Issue by kevin11h** [play-with-docker/play-with-docker#265]
We are building a MOOC and hope to use docker for setup environment, but have problems how to get Play-with-Docker on Amazon AWS. Any intuitions how to solve this issue?

**Comment by m4r10k** [comment]
@kevin11h I wrote a blog post about how to run PWD on AWS because I had the need for it too. Sometimes at our Docker Meetups it is useful to have a local and or self hosted (AWS) PWD setup at hand. Better a late than never :smiley: https://www.n0r1sk.com/index.php/2018/12/28/running-play-with-docker-on-aws/ Happy new year!

**Comment by marcosnils** [comment]
Thx. I'll close this issue to avoid confusions

**Comment by ebartz** [comment]
@m4r10k , thanks for writing the playbook. I was trying to get it to work but after clicking on "Start" I get the following error:

```
PANIC: runtime error: invalid memory address or nil pointer dereference
goroutine 47 [running]:
github.com/play-with-docker/play-with-docker/vendor/github.com/urfave/negroni.(*Recovery).ServeHTTP.func1(0x7ffabc568290, 0xc0003b4540, 0xc00017e820)
	/go/src/github.com/play-with-docker/play-with-docker/vendor/github.com/urfave/negroni/recovery.go:34 +0xe8
panic(0x1521720, 0x284e160)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/play-with-docker/play-with-docker/pwd.(*pwd).SessionNew(0xc0003c6240, 0x19be380, 0xc000042170, 0xc0003d9c20, 0x0, 0x0, 0xd18c2e28000, 0xc000041880, 0x0, 0xc000041887, ...)
	/go/src/github.com/play-with-docker/play-with-docker/pwd/session.go:50 +0xd9
github.com/play-with-docker/play-with-docker/handlers.NewSession(0x7ffabc568290, 0xc0003b4580, 0xc000414b00)
	/go/src/github.com/play-with-docker/play-with-docker/handlers/new_session.go:81 +0x282
net/http.HandlerFunc.ServeHTTP(0x17a6ef8, 0x7ffabc568290, 0xc0003b4580, 0xc000414b00)
	/usr/local/go/src/net/http/server.go:1995 +0x44
github.com/play-with-docker/play-with-docker/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc00039a720, 0x7ffabc568290, 0xc0003b4580, 0xc000414b00)
	/go/src/github.com/play-with-docker/play-with-docker/vendor/github.com/gorilla/mux/mux.go:133 +0xec
github.com/play-with-docker/play-with-docker/vendor/github.com/gorilla/handlers.(*cors).ServeHTTP(0xc0002cdb00, 0x7ffabc568290, 0xc0003b4580, 0xc000414700)
	/go/src/github.com/play-with-docker/play-with-docker/vendor/github.com/gorilla/handlers/cors.go:51 +0x101f
github.com/play-with-docker/play-with-docker/vendor/github.com/urfave/negroni.Wrap.func1(0x7ffabc568290, 0xc0003b4580, 0xc000414700, 0xc0005381c0)
	/go/src/github.com/play-with-docker/play-with-docker/vendor/github.com/urfave/negroni/negroni.go:41 +0x4d
github.com/play-with-docker/play-with-docker/vendor/github.com/urfave/negroni.HandlerFunc.ServeHTTP(0xc00017e960, 0x7ffabc568290, 0xc0003b4580, 0xc000414700, 0xc0005381c0)
	/go/src/github.com/play-with-docker/play-with-docker/vendor/github.com/urfave/negroni/negroni.go:24 +0x4e
github.com/play-with-docker/play-with-docker/vendor/github.com/urfave/negroni.middleware.ServeHTTP(0x198eb00, 0xc00017e960, 0xc00017eb20, 0x7ffabc568290, 0xc0003b4580, 0xc000414700)
	/go/src/github.com/play-with-docker/play-with-docker/vendor/github.com/urfave/negroni/negroni.go:33 +0x9c
github.com/play-with-docker/play-with-docker/vendor/github.com/urfave/negroni.(*Negroni).ServeHTTP(0xc0003940f0, 0x7ffabc568290, 0xc0003b4540, 0xc000414700)
	/go/src/github.com/play-with-docker/play-with-docker/vendor/github.com/urfave/negroni/negroni.go:73 +0xe9
github.com/play-with-docker/play-with-docker/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc00039a6c0, 0x7ffabc568290, 0xc0003b4540, 0xc000414700)
	/go/src/github.com/play-with-docker/play-with-docker/vendor/github.com/gorilla/mux/mux.go:133 +0xec
github.com/play-with-docker/play-with-docker/vendor/github.com/urfave/negroni.Wrap.func1(0x7ffabc568290, 0xc0003b4540, 0xc000414500, 0xc0005381a0)
	/go/src/github.com/play-with-docker/play-with-docker/vendor/github.com/urfave/negroni/negroni.go:41 +0x4d
github.com/play-with-docker/play-with-docker/vendor/github.com/urfave/negroni.HandlerFunc.ServeHTTP(0xc00017eb60, 0x7ffabc568290, 0xc0003b4540, 0xc000414500, 0xc0005381a0)
	/go/src/github.com/play-with-docker/play-with-docker/vendor/github.com/urfave/negroni/negroni.go:24 +0x4e
github.com/play-with-docker/play-with-docker/vendor/github.com/urfave/negroni.middleware.ServeHTTP(0x198eb00, 0xc00017eb60, 0xc00017ec00, 0x7ffabc568290, 0xc0003b4540, 0xc000414500)
	/go/src/github.com/play-with-docker/play-with-docker/vendor/github.com/urfave/negroni/negroni.go:33 +0x9c
github.com/play-with-docker/play-with-docker/vendor/github.com/urfave/negroni.(*Static).ServeHTTP(0xc000285f20, 0x7ffabc568290, 0xc0003b4540, 0xc000414500, 0xc000538180)
	/go/src/github.com/play-with-docker/play-with-docker/vendor/github.com/urfave/negroni/static.go:30 +0x79
github.com/play-with-docker/play-with-docker/vendor/github.com/urfave/negroni.middleware.ServeHTTP(0x198d320, 0xc000285f20, 0xc00017ebe0, 0x7ffabc568290, 0xc0003b4540, 0xc000414500)
	/go/src/github.com/play-with-docker/play-with-docker/vendor/github.com/urfave/negroni/negroni.go:33 +0x9c
github.com/play-with-docker/play-with-docker/vendor/github.com/urfave/negroni.(*Logger).ServeHTTP(0xc000010498, 0x7ffabc568290, 0xc0003b4540, 0xc000414500, 0xc000538160)
	/go/src/github.com/play-with-docker/play-with-docker/vendor/github.com/urfave/negroni/logger.go:25 +0x15c
github.com/play-with-docker/play-with-docker/vendor/github.com/urfave/negroni.middleware.ServeHTTP(0x198d2c0, 0xc000010498, 0xc00017ebc0, 0x7ffabc568290, 0xc0003b4540, 0xc000414500)
	/go/src/github.com/play-with-docker/play-with-docker/vendor/github.com/urfave/negroni/negroni.go:33 +0x9c
github.com/play-with-docker/play-with-docker/vendor/github.com/urfave/negroni.(*Recovery).ServeHTTP(0xc00017e820, 0x7ffabc568290, 0xc0003b4540, 0xc000414500, 0xc000538140)
	/go/src/github.com/play-with-docker/play-with-docker/vendor/github.com/urfave/negroni/recovery.go:45 +0x82
github.com/play-with-docker/play-with-docker/vendor/github.com/urfave/negroni.middleware.ServeHTTP(0x198d300, 0xc00017e820, 0xc00017eb80, 0x7ffabc568290, 0xc0003b4540, 0xc000414500)
	/go/src/github.com/play-with-docker/play-with-docker/vendor/github.com/urfave/negroni/negroni.go:33 +0x9c
github.com/play-with-docker/play-with-docker/vendor/github.com/urfave/negroni.(*Negroni).ServeHTTP(0xc000285f80, 0x19b5cc0, 0xc00010e0e0, 0xc000414500)
	/go/src/github.com/play-with-docker/play-with-docker/vendor/github.com/urfave/negroni/negroni.go:73 +0xe9
net/http.serverHandler.ServeHTTP(0xc00047edd0, 0x19b5cc0, 0xc00010e0e0, 0xc000414500)
	/usr/local/go/src/net/http/server.go:2774 +0xab
net/http.(*conn).serve(0xc000370000, 0x19be340, 0xc0003b4000)
	/usr/local/go/src/net/http/server.go:1878 +0x84c
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2884 +0x2f4
```

Is that me doing something wrong, or does it just not work currently?

**Comment by m4r10k** [comment]
@ebartz I will look into this in about a week or two, as I will refresh this setup for a our Docker Meetup at the end of March. But to unterstand you correctly: The setup is running, you already see the PWD homepage and then, when you click start, you get this exception? Correct?

**Comment by ebartz** [comment]
Yep. you can check it at http://pwd.sva.hamburg/

**Comment by ebartz** [comment]
Seems like a bug with the pwd code. I went back to commit 857bbe30cb05dde55f852a45a3d8c1dc6fa1d9b7 and there everything works fine.

**Comment by m4r10k** [comment]
Cool! I am happy that it still works and that this setup is useful for you!

Enrico Bartz <notifications@github.com> schrieb am So., 10. März 2019,
16:21:

**Comment by marcosnils** [comment]
@ebartz I've pushed some code that fixes the panic error you were getting.

**Comment by m4r10k** [comment]
@marcosnils Thank you! Really cool!
